# Main file for project (Flashcard Quiz App)

# Luis Daniel Hernandez from CS210 class, group Copernicus
# Lab 5: File Handling and Exceptions

# Initialize OpenAI client
import random
import os
from google import genai
from rapidfuzz import fuzz   # type: ignore


class Flashcard:
    def __init__(self, question, answer):
        self.question = question
        self.answer = answer


def generate_flashcards(topic, num_cards=5):
    """
    Use Gemini to generate flashcards.
    """
    flashcards = []

    client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

    # Prompt Gemini to create flashcards, important to be specific
    prompt = (
        f"Generate {num_cards} flashcards about '{topic}'. "
        "Each flashcard MUST follow this format exactly: Question?|Answer\n"
        "- The answer MUST be 1 to 3 words only.\n"
        "- The answer MUST NOT contain punctuation of any kind.\n"
        "- The answer MUST be simple and easy to guess.\n"
        "- The question should be clear and short.\n"
        "- Do NOT number the flashcards.\n"
        "Output exactly one flashcard per line."
        )
    
    response = client.models.generate_content(
        model="gemini-2.5-flash", 
        contents=prompt,
        )

    text = response.text

    for line in text.split("\n"):
        if "|" in line:
            q, a = line.split("|", 1)

            # Guarantee cleanup even if model slips
            q = q.strip()
            a = a.strip()
            a = a.replace(".", "").replace(",", "").replace("!", "").replace("?", "")
            # Limit answer to max 3 words
            a = " ".join(a.split()[:3])
            a = a.lower()

            flashcards.append(Flashcard(q.strip(), a.strip()))

    return flashcards


def quiz_user(flashcards):
    if not flashcards:
        print("No flashcards available. Exiting quiz.")
        return

    score = 0
    random.shuffle(flashcards)

    for card in flashcards:
        print(f"\nQuestion: {card.question}")
        guesses = 0
        correct = False

        while guesses < 3 and not correct:
            user_answer = input(f"Your answer (guess {guesses+1}/3): ").strip()
            guesses += 1
            if is_semantically_close(user_answer, card.answer):
                print("✅ Correct!\n")
                score += 1
                correct = True
            elif guesses < 3:
                print("❌ Incorrect. Try again.\n")
            else:
                print(f"❌ Wrong! The correct answer is: {card.answer}\n")

    print(f"\nYour final score: {score}/{len(flashcards)}")


def save_flashcards_to_file(flashcards, filename="ai_questions.txt"):
    try:
        with open(filename, "w") as file:
            for card in flashcards:
                file.write(f"{card.question}|{card.answer}\n")
        print(f"\nAI-generated flashcards saved to '{filename}'")
    except Exception as e:
        print(f"Error saving file: {e}")


def is_semantically_close(user_answer, correct_answer, threshold=70):
    similarity = fuzz.ratio(user_answer.lower(), correct_answer.lower())
    return similarity >= threshold


def main():
    print("=== Gemini AI Flashcard Quiz App ===")
    topic = input("Enter a topic for the flashcards (e.g., 'Python programming'): ").strip()
    num = input("How many flashcards do you want? (default 5): ").strip()
    num = int(num) if num.isdigit() else 5

    flashcards = generate_flashcards(topic, num)
    print(f"\nGenerated {len(flashcards)} flashcards on '{topic}'. Let's start the quiz!")
    # ⭐ Save flashcards generated by Gemini
    save_flashcards_to_file(flashcards)

    quiz_user(flashcards)


if __name__ == "__main__":
    main()

