# Main file for project (Flashcard Quiz App)

# Luis Daniel Hernandez from CS210 class, group Copernicus
# Lab 5: File Handling and Exceptions

# Initialize OpenAI client
import random
import os
from google import genai


class Flashcard:
    def __init__(self, question, answer):
        self.question = question
        self.answer = answer


def generate_flashcards(topic, num_cards=5):
    """
    Use Gemini to generate flashcards.
    """
    flashcards = []

    client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

    prompt = f"Generate {num_cards} simple Q&A flashcards about '{topic}'. Format each flashcard as 'Question?|Answer'."

    response = client.models.generate_content(
        model="gemini-2.5-flash", 
        contents=prompt,
        )

    text = response.text

    for line in text.split("\n"):
        if "|" in line:
            q, a = line.split("|", 1)
            flashcards.append(Flashcard(q.strip(), a.strip()))

    return flashcards


def quiz_user(flashcards):
    if not flashcards:
        print("No flashcards available. Exiting quiz.")
        return

    score = 0
    random.shuffle(flashcards)

    for card in flashcards:
        print(f"\nQuestion: {card.question}")
        guesses = 0
        correct = False

        while guesses < 3 and not correct:
            user_answer = input(f"Your answer (guess {guesses+1}/3): ").strip()
            guesses += 1
            if user_answer.lower() == card.answer.lower():
                print("✅ Correct!\n")
                score += 1
                correct = True
            elif guesses < 3:
                print("❌ Incorrect. Try again.\n")
            else:
                print(f"❌ Wrong! The correct answer is: {card.answer}\n")

    print(f"\nYour final score: {score}/{len(flashcards)}")

def save_flashcards_to_file(flashcards, filename="ai_questions.txt"):
    try:
        with open(filename, "w") as file:
            for card in flashcards:
                file.write(f"{card.question}|{card.answer}\n")
        print(f"\nAI-generated flashcards saved to '{filename}'")
    except Exception as e:
        print(f"Error saving file: {e}")

def main():
    print("=== Gemini AI Flashcard Quiz App ===")
    topic = input("Enter a topic for the flashcards (e.g., 'Python programming'): ").strip()
    num = input("How many flashcards do you want? (default 5): ").strip()
    num = int(num) if num.isdigit() else 5

    flashcards = generate_flashcards(topic, num)
    print(f"\nGenerated {len(flashcards)} flashcards on '{topic}'. Let's start the quiz!")
    # ⭐ Save flashcards generated by Gemini
    save_flashcards_to_file(flashcards)

    quiz_user(flashcards)


if __name__ == "__main__":
    main()

